baseline_parameters:
  season_start: 2024-09-29
  season_end: 2025-03-23
  births_path: input/births.csv
  weights_path: data/weights.csv
  interval: week # birth cohort interval
  uptake: 1.0

grid_parameters:
  scenario: [highest_100, middle_100, lowest_100]

nested_parameters:
  - scenario: highest_100
    growth_chart: WHO
    p_high_risk: 0.04
    delays: # 20% delay by 8 weeks
      0: 0.8
      8: 0.2
  - scenario: middle_100
    growth_chart: WHO
    p_high_risk: 0.03
    delays:
      0: 0.8
      4: 0.2
  - scenario: lowest_100
    growth_chart: CDC
    p_high_risk: 0.02
    delays:
      0: 1.0
